on: 
  push:
    branches:
      - main

jobs:
  get_version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
      - id: update_release
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: node -e "let manifest = require('./package.json'); console.log('ver=' + manifest.version)" >> "${GITHUB_OUTPUT}"
      - run: echo last_tag="$(git describe --tags)" >> "${GITHUB_OUTPUT}"
      - if: ${{ steps.update_release.outputs.ver == steps.update_release.outputs.last_tag }}
        run: |
          curl -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{github.token}}" \
          https://api.github.com/repos/${{ github.repository }}/releases \
          -d '{ "tag_name": "${{ steps.check_ver.outputs.ver }}", "target_commitish": "main", "generate_release_notes": true}'
